### ISSUE TITLE
A nice extra to your addon would be a test if real debrid blocks the current IP address

### ISSUE THREAD

**Issue by peno64** [a4k-openproject/plugin.program.openwizard#63]
I have written a small addon that goes to page https://real-debrid.com/vpn and scrapes the info on that page and presents it in kodi.
This page checks if the current ip is blocked by real debrid or not. This happens often with vpn's

You can find my addon here: https://github.com/peno64/script.RealDebrid.vpn

I think it would be a nice extra to your addon to have this also.

**Comment by drinfernoo** [comment]
While I do think an add-on like has value, I don't really think it fits within the scope of OpenWizard. Sorry!

**Comment by peno64** [comment]
Ok no problem for me but a bit strange since yoy have tools like speedtester and clear cache and change advanced settings so what is the scope?
________________________________

**Comment by drinfernoo** [comment]
OpenWizard is for maintaining and managing your Kodi install and related files. It doesn't contact out to any external APIs, and doesn't have authentication with any either. The wizard would have to be authorized with Real-Debrid itself, in order to even do this.

Like I said, an add-on that does test this, and other external APIs, would be a welcome newcomer to the scene, but I don't think it fits with this project.

**Comment by peno64** [comment]
Ok no problem. But note that no autorization to real debrid is needed. Anyone can go to that page to see if his ip adres is blocked or not.
________________________________
