### ISSUE TITLE
User Customisations Kept After OpenWizard Update Issued?

### ISSUE THREAD

**Issue by Jeffers24** [a4k-openproject/plugin.program.openwizard#86]
I may be miss using this system, I say that because my post is just a query?

If I customise your openwizard as detailed in the wiki, will my changes be overwritten/lost when you issue an update via your repository?

**Comment by drinfernoo** [comment]
As long as you change the add-on ID, then they won't.

**Comment by Jeffers24** [comment]
Thanks for response.

If I change the add-on ID will that mean my version with a changed ID will never get any updates?

I notice there is an OpenWizard folder in the Userdata folder which contains a settings file. I am assuming this will never be overwritten/updated when a new version of OpenWizard is installed automatically from your repo. Is my assumption correct?

**Comment by SerpentDrago** [comment]
Change the ID and install that now forked / changed wizard .  and a new userdata folder with that id will be created . 

ID's are what matter as far as kodi in concerned . New id , new settings folder , kodi treats it as a different addon .

Which is why if you make modifications you should change the ID at the very least . so it doesn't get overwritten

**Comment by drinfernoo** [comment]
@Jeffers24 The `special://userdata/addon_data/plugin.program.openwizard/` folder stores the users settings for the add-on, and won't be overwritten by an update, but could be changed.

By changing the ID of your customized wizard, you won't receive further updates and will have to diff and merge the changes into your wizard.
